crown5=int(input("How many crown five coins are in your pocket: "))
crown2=int(input("How many crown two coins are in your pocket: "))
crown1=int(input("How many crown one coins are in your pocket: "))
pocket=int(crown5*5+crown2*2+crown1)
print(pocket)